package config

const (
	SupabaseURL = "https://ytqxnxhkvqszwsdkrwgg.supabase.co"
	SupabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0cXhueGhrdnFzendzZGtyd2dnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNDI2OTI3MywiZXhwIjoyMDQ5ODQ1MjczfQ.b5J1_JXgjnKasALeNlC4AlRWQJ0lt7Fd-vu3l49aM8A"
)
